# Generated by Django 3.2.23 on 2026-01-19 02:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('join_date', models.DateTimeField(auto_now_add=True)),
                ('interests', models.JSONField(default=list)),
                ('profile_photo', models.CharField(blank=True, max_length=500, null=True)),
                ('streak_days', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('active_time', models.IntegerField(default=0)),
                ('last_session_time', models.IntegerField(default=0)),
                ('last_session_update', models.DateTimeField(blank=True, null=True)),
                ('daily_activity', models.JSONField(default=dict)),
                ('reset_token', models.CharField(blank=True, max_length=255, null=True)),
                ('reset_token_expires', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='EmailOTP',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('otp', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('is_verified', models.BooleanField(default=False)),
                ('attempts', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'email_otps',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Interaction',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=200)),
                ('article_id', models.CharField(max_length=200)),
                ('action', models.CharField(choices=[('like', 'Like'), ('dislike', 'Dislike'), ('comment', 'Comment'), ('share', 'Share'), ('save', 'Save'), ('read', 'Read'), ('ai_snapshot', 'AI Snapshot')], max_length=50)),
                ('sentiment', models.FloatField(default=0.0)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('comment_text', models.TextField(blank=True, null=True)),
                ('dwell_time', models.IntegerField(default=0, help_text='Time spent on article in seconds')),
            ],
            options={
                'db_table': 'interactions',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='KnowledgeBox',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.CharField(db_index=True, max_length=200)),
                ('topic', models.CharField(max_length=200)),
                ('article_count', models.IntegerField(default=0)),
                ('total_time_spent', models.IntegerField(default=0)),
                ('importance_score', models.FloatField(default=0.0)),
                ('subtopics', models.JSONField(default=list)),
                ('key_entities', models.JSONField(default=list)),
                ('article_ids', models.JSONField(default=list)),
                ('first_read', models.DateTimeField(auto_now_add=True)),
                ('last_read', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'knowledge_box',
                'ordering': ['-importance_score', '-last_read'],
            },
        ),
        migrations.CreateModel(
            name='NewsArticle',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500)),
                ('summary', models.TextField()),
                ('content', models.TextField()),
                ('category', models.CharField(db_index=True, max_length=100)),
                ('source', models.CharField(blank=True, default='Unknown', max_length=200, null=True)),
                ('source_id', models.CharField(blank=True, max_length=200, null=True)),
                ('publish_time', models.DateTimeField(db_index=True, default=datetime.datetime.now)),
                ('sentiment_score', models.FloatField(default=0.0)),
                ('image_url', models.CharField(blank=True, max_length=500, null=True)),
                ('is_spam', models.BooleanField(default=False)),
                ('url', models.CharField(blank=True, max_length=500, null=True)),
                ('author', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'news_articles',
                'ordering': [],
            },
        ),
        migrations.CreateModel(
            name='NewsSource',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('api_url', models.CharField(max_length=500)),
                ('type', models.CharField(choices=[('API', 'API'), ('RSS', 'RSS'), ('SocialMedia', 'Social Media')], max_length=50)),
                ('credibility_score', models.FloatField(default=0.5)),
            ],
            options={
                'db_table': 'news_sources',
            },
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=200)),
                ('article_ids', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('model_version', models.CharField(default='v1.0', max_length=50)),
            ],
            options={
                'db_table': 'recommendations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserPreference',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=100)),
                ('preference_score', models.FloatField(default=0.5)),
                ('interaction_count', models.IntegerField(default=0)),
                ('total_dwell_time', models.IntegerField(default=0)),
                ('last_interaction', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'user_preferences',
            },
        ),
        migrations.AddIndex(
            model_name='userpreference',
            index=models.Index(fields=['user_id', 'preference_score'], name='user_prefer_user_id_0ba49d_idx'),
        ),
        migrations.AddIndex(
            model_name='knowledgebox',
            index=models.Index(fields=['user_id', '-importance_score'], name='knowledge_b_user_id_4ffa06_idx'),
        ),
    ]
