# Generated by Django 3.2.23 on 2026-01-20 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='reset_otp',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='reset_otp_expires',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
